CREATE TABLE community_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    slug VARCHAR(80) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_community_categories_slug UNIQUE (slug)
);

CREATE TABLE communities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id BIGINT NOT NULL,
    category_id BIGINT,
    slug VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    avatar_asset_id BIGINT,
    cover_asset_id BIGINT,
    visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    member_count BIGINT NOT NULL DEFAULT 0,
    online_count BIGINT NOT NULL DEFAULT 0,
    default_channel_id BIGINT,
    CONSTRAINT uk_communities_slug UNIQUE (slug),
    CONSTRAINT fk_communities_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_communities_category FOREIGN KEY (category_id) REFERENCES community_categories (id),
    CONSTRAINT fk_communities_avatar_asset FOREIGN KEY (avatar_asset_id) REFERENCES uploaded_assets (id),
    CONSTRAINT fk_communities_cover_asset FOREIGN KEY (cover_asset_id) REFERENCES uploaded_assets (id),
    CONSTRAINT ck_communities_visibility CHECK (visibility IN ('PUBLIC', 'PRIVATE', 'UNLISTED')),
    CONSTRAINT ck_communities_status CHECK (status IN ('ACTIVE', 'ARCHIVED', 'SUSPENDED'))
);

CREATE TABLE community_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    slug VARCHAR(80) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_community_tags_slug UNIQUE (slug)
);

CREATE TABLE community_tag_links (
    community_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    CONSTRAINT pk_community_tag_links PRIMARY KEY (community_id, tag_id),
    CONSTRAINT fk_community_tag_links_community FOREIGN KEY (community_id) REFERENCES communities (id),
    CONSTRAINT fk_community_tag_links_tag FOREIGN KEY (tag_id) REFERENCES community_tags (id)
);

CREATE TABLE community_members (
    community_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_community_members PRIMARY KEY (community_id, user_id),
    CONSTRAINT fk_community_members_community FOREIGN KEY (community_id) REFERENCES communities (id),
    CONSTRAINT fk_community_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_community_members_role CHECK (role IN ('OWNER', 'ADMIN', 'MODERATOR', 'MEMBER')),
    CONSTRAINT ck_community_members_status CHECK (status IN ('ACTIVE', 'PENDING', 'LEFT', 'BANNED'))
);

CREATE TABLE community_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    community_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    slug VARCHAR(80) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    type VARCHAR(20) NOT NULL DEFAULT 'TEXT',
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_read_only BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NOT NULL,
    CONSTRAINT uk_community_channels_community_slug UNIQUE (community_id, slug),
    CONSTRAINT uk_community_channels_conversation UNIQUE (conversation_id),
    CONSTRAINT fk_community_channels_community FOREIGN KEY (community_id) REFERENCES communities (id),
    CONSTRAINT fk_community_channels_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id),
    CONSTRAINT fk_community_channels_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_community_channels_type CHECK (type IN ('TEXT', 'ANNOUNCEMENT', 'SIGNALS', 'EDUCATION')),
    CONSTRAINT ck_community_channels_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

ALTER TABLE communities
    ADD CONSTRAINT fk_communities_default_channel
        FOREIGN KEY (default_channel_id) REFERENCES community_channels (id);

CREATE INDEX idx_communities_category_status
    ON communities (category_id, status, member_count DESC, id DESC);

CREATE INDEX idx_communities_visibility_status
    ON communities (visibility, status, member_count DESC, id DESC);

CREATE INDEX idx_community_members_user_status
    ON community_members (user_id, status, joined_at DESC);

CREATE INDEX idx_community_members_community_status
    ON community_members (community_id, status, joined_at DESC);

CREATE INDEX idx_community_channels_community_sort
    ON community_channels (community_id, status, sort_order, id);

CREATE INDEX idx_community_tag_links_tag
    ON community_tag_links (tag_id, community_id);

INSERT INTO community_categories (slug, name, description, sort_order) VALUES
    ('technical', 'Technical', 'Chart analysis and trading setups.', 10),
    ('signals', 'Signals', 'Market signals and watchlists.', 20),
    ('news', 'News', 'Headlines, catalysts, and policy updates.', 30),
    ('education', 'Education', 'Learning rooms and trading school.', 40),
    ('on-chain', 'On-chain', 'Wallet flows, protocol activity, and network data.', 50),
    ('memes', 'Memes', 'Narrative discovery and social momentum.', 60);

INSERT INTO community_tags (slug, name) VALUES
    ('technical', 'Technical'),
    ('signals', 'Signals'),
    ('news', 'News'),
    ('education', 'Education'),
    ('on-chain', 'On-chain'),
    ('memes', 'Memes'),
    ('macro', 'Macro'),
    ('risk', 'Risk'),
    ('social', 'Social');
