CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recipient_id BIGINT NOT NULL,
    actor_id BIGINT,
    type VARCHAR(30) NOT NULL,
    title VARCHAR(150) NOT NULL,
    body VARCHAR(500),
    target_type VARCHAR(30),
    target_id BIGINT,
    source_type VARCHAR(30),
    source_id BIGINT,
    dedupe_key VARCHAR(150),
    read_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users (id),
    CONSTRAINT fk_notifications_actor FOREIGN KEY (actor_id) REFERENCES users (id),
    CONSTRAINT uk_notifications_recipient_dedupe UNIQUE (recipient_id, dedupe_key),
    CONSTRAINT ck_notifications_type CHECK (type IN ('PRICE_ALERT', 'COMMUNITY', 'MENTION', 'SYSTEM')),
    CONSTRAINT ck_notifications_target_type CHECK (
        target_type IS NULL
        OR target_type IN ('MARKET_ASSET', 'PRICE_ALERT', 'COMMUNITY', 'CONVERSATION', 'MESSAGE')
    ),
    CONSTRAINT ck_notifications_target_value CHECK (
        (target_type IS NULL AND target_id IS NULL)
        OR (target_type IS NOT NULL AND target_id IS NOT NULL AND target_id > 0)
    ),
    CONSTRAINT ck_notifications_source_value CHECK (
        (source_type IS NULL AND source_id IS NULL)
        OR (source_type IS NOT NULL AND source_id IS NOT NULL AND source_id > 0)
    )
);

CREATE INDEX idx_notifications_recipient_created
    ON notifications (recipient_id, created_at DESC, id DESC);

CREATE INDEX idx_notifications_recipient_read
    ON notifications (recipient_id, read_at);

CREATE INDEX idx_notifications_source
    ON notifications (source_type, source_id);
