CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    avatar_url VARCHAR(500),
    bio VARCHAR(500),
    account_status VARCHAR(20) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE presences (
    user_id BIGINT PRIMARY KEY,
    is_online BOOLEAN NOT NULL DEFAULT FALSE,
    last_active_at TIMESTAMP WITH TIME ZONE,
    connection_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_presences_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type VARCHAR(20) NOT NULL,
    last_message_id BIGINT,
    last_message_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE conversation_participants (
    conversation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_read_message_id BIGINT,
    unread_count BIGINT NOT NULL DEFAULT 0,
    is_visible_in_list BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_conversation_participants PRIMARY KEY (conversation_id, user_id),
    CONSTRAINT fk_conversation_participants_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id),
    CONSTRAINT fk_conversation_participants_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    client_message_id UUID NOT NULL,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content VARCHAR(4000) NOT NULL,
    message_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    delivered_at TIMESTAMP WITH TIME ZONE,
    read_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_messages_conversation_client_message_id UNIQUE (conversation_id, client_message_id),
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id),
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id)
);

CREATE INDEX idx_users_account_status ON users (account_status);
CREATE INDEX idx_conversation_participants_user_visible ON conversation_participants (user_id, is_visible_in_list);
CREATE INDEX idx_conversation_participants_conversation ON conversation_participants (conversation_id);
CREATE INDEX idx_conversations_last_message_at_id ON conversations (last_message_at DESC, id DESC);
CREATE INDEX idx_messages_conversation_created_id ON messages (conversation_id, created_at DESC, id DESC);
CREATE INDEX idx_messages_conversation_read ON messages (conversation_id, read_at);
CREATE INDEX idx_messages_sender ON messages (sender_id);
