ALTER TABLE messages ADD COLUMN edited_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE messages ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE messages ADD COLUMN deleted_by BIGINT;
ALTER TABLE messages ADD COLUMN reply_to_message_id BIGINT;

ALTER TABLE messages
    ADD CONSTRAINT fk_messages_deleted_by
        FOREIGN KEY (deleted_by) REFERENCES users (id);

ALTER TABLE messages
    ADD CONSTRAINT fk_messages_reply_to_message
        FOREIGN KEY (reply_to_message_id) REFERENCES messages (id);

CREATE TABLE message_pins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    conversation_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    pinned_by BIGINT NOT NULL,
    pinned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_message_pins_conversation_message UNIQUE (conversation_id, message_id),
    CONSTRAINT fk_message_pins_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id),
    CONSTRAINT fk_message_pins_message FOREIGN KEY (message_id) REFERENCES messages (id),
    CONSTRAINT fk_message_pins_pinned_by FOREIGN KEY (pinned_by) REFERENCES users (id)
);

CREATE TABLE message_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    emoji VARCHAR(32) NOT NULL,
    CONSTRAINT uk_message_reactions_message_user_emoji UNIQUE (message_id, user_id, emoji),
    CONSTRAINT fk_message_reactions_message FOREIGN KEY (message_id) REFERENCES messages (id),
    CONSTRAINT fk_message_reactions_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_messages_reply_to_message_id ON messages (reply_to_message_id);
CREATE INDEX idx_messages_deleted_at ON messages (deleted_at);
CREATE INDEX idx_message_pins_conversation_pinned_at ON message_pins (conversation_id, pinned_at DESC);
CREATE INDEX idx_message_pins_message ON message_pins (message_id);
CREATE INDEX idx_message_reactions_message ON message_reactions (message_id);
CREATE INDEX idx_message_reactions_user ON message_reactions (user_id);
