ALTER TABLE messages ALTER COLUMN content DROP NOT NULL;

CREATE TABLE message_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message_id BIGINT NOT NULL,
    object_key VARCHAR(1000) NOT NULL,
    url VARCHAR(2000),
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    width INTEGER,
    height INTEGER,
    duration_seconds INTEGER,
    thumbnail_url VARCHAR(2000),
    sort_order INTEGER NOT NULL,
    CONSTRAINT fk_message_attachments_message FOREIGN KEY (message_id) REFERENCES messages (id)
);

CREATE INDEX idx_message_attachments_message_sort
    ON message_attachments (message_id, sort_order, id);
