CREATE TABLE upload_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id BIGINT NOT NULL,
    purpose VARCHAR(50) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    chunk_size_bytes BIGINT NOT NULL,
    total_parts INTEGER NOT NULL,
    object_key VARCHAR(1000) NOT NULL,
    r2_upload_id VARCHAR(1000) NOT NULL,
    file_checksum VARCHAR(128),
    status VARCHAR(30) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_upload_sessions_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT uk_upload_sessions_object_key UNIQUE (object_key)
);

CREATE TABLE upload_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    upload_session_id BIGINT NOT NULL,
    part_number INTEGER NOT NULL,
    etag VARCHAR(500) NOT NULL,
    size_bytes BIGINT NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_upload_parts_session FOREIGN KEY (upload_session_id) REFERENCES upload_sessions (id),
    CONSTRAINT uk_upload_parts_session_part UNIQUE (upload_session_id, part_number)
);

CREATE TABLE uploaded_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id BIGINT NOT NULL,
    upload_session_id BIGINT NOT NULL,
    purpose VARCHAR(50) NOT NULL,
    object_key VARCHAR(1000) NOT NULL,
    public_url VARCHAR(2000),
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    width INTEGER,
    height INTEGER,
    duration_seconds INTEGER,
    thumbnail_url VARCHAR(2000),
    status VARCHAR(30) NOT NULL,
    attached_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_uploaded_assets_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_uploaded_assets_session FOREIGN KEY (upload_session_id) REFERENCES upload_sessions (id),
    CONSTRAINT uk_uploaded_assets_session UNIQUE (upload_session_id),
    CONSTRAINT uk_uploaded_assets_object_key UNIQUE (object_key)
);

ALTER TABLE message_attachments
    ADD COLUMN uploaded_asset_id BIGINT;

ALTER TABLE message_attachments
    ADD CONSTRAINT fk_message_attachments_uploaded_asset
        FOREIGN KEY (uploaded_asset_id) REFERENCES uploaded_assets (id);

CREATE INDEX idx_upload_sessions_owner_status
    ON upload_sessions (owner_id, status, created_at DESC);

CREATE INDEX idx_upload_parts_session
    ON upload_parts (upload_session_id, part_number);

CREATE INDEX idx_uploaded_assets_owner_status
    ON uploaded_assets (owner_id, status, created_at DESC);