CREATE TABLE market_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    coingecko_id VARCHAR(100) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    image_url VARCHAR(500),
    market_cap_rank INTEGER,
    current_price_usd NUMERIC(30, 12),
    price_change_percentage_24h NUMERIC(20, 8),
    high_24h NUMERIC(30, 12),
    low_24h NUMERIC(30, 12),
    market_cap NUMERIC(30, 2),
    total_volume NUMERIC(30, 2),
    circulating_supply NUMERIC(30, 12),
    total_supply NUMERIC(30, 12),
    max_supply NUMERIC(30, 12),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_market_assets_coingecko_id UNIQUE (coingecko_id)
);

CREATE TABLE market_pairs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    asset_id BIGINT NOT NULL,
    exchange VARCHAR(30) NOT NULL,
    base_symbol VARCHAR(20) NOT NULL,
    quote_symbol VARCHAR(20) NOT NULL,
    symbol VARCHAR(40) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_market_pairs_exchange_symbol UNIQUE (exchange, symbol),
    CONSTRAINT fk_market_pairs_asset FOREIGN KEY (asset_id) REFERENCES market_assets (id)
);

CREATE TABLE market_candles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pair_id BIGINT NOT NULL,
    interval_name VARCHAR(10) NOT NULL,
    open_time TIMESTAMP WITH TIME ZONE NOT NULL,
    close_time TIMESTAMP WITH TIME ZONE NOT NULL,
    open NUMERIC(30, 12) NOT NULL,
    high NUMERIC(30, 12) NOT NULL,
    low NUMERIC(30, 12) NOT NULL,
    close NUMERIC(30, 12) NOT NULL,
    volume NUMERIC(30, 12) NOT NULL,
    quote_volume NUMERIC(30, 12) NOT NULL,
    trade_count BIGINT NOT NULL DEFAULT 0,
    is_closed BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_market_candles_pair_interval_open_time UNIQUE (pair_id, interval_name, open_time),
    CONSTRAINT fk_market_candles_pair FOREIGN KEY (pair_id) REFERENCES market_pairs (id)
);

CREATE TABLE market_trending (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    asset_id BIGINT,
    coingecko_id VARCHAR(100) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    thumb_url VARCHAR(500),
    market_cap_rank INTEGER,
    score INTEGER NOT NULL DEFAULT 0,
    snapshot_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_market_trending_coingecko_id UNIQUE (coingecko_id),
    CONSTRAINT fk_market_trending_asset FOREIGN KEY (asset_id) REFERENCES market_assets (id)
);

CREATE TABLE user_watchlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    CONSTRAINT uk_user_watchlist_items_user_asset UNIQUE (user_id, asset_id),
    CONSTRAINT fk_user_watchlist_items_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_watchlist_items_asset FOREIGN KEY (asset_id) REFERENCES market_assets (id)
);

CREATE TABLE price_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    pair_id BIGINT,
    condition_type VARCHAR(20) NOT NULL,
    target_price NUMERIC(30, 12),
    target_percent NUMERIC(20, 8),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    triggered_at TIMESTAMP WITH TIME ZONE,
    last_checked_at TIMESTAMP WITH TIME ZONE,
    last_triggered_price NUMERIC(30, 12),
    CONSTRAINT fk_price_alerts_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_price_alerts_asset FOREIGN KEY (asset_id) REFERENCES market_assets (id),
    CONSTRAINT fk_price_alerts_pair FOREIGN KEY (pair_id) REFERENCES market_pairs (id),
    CONSTRAINT ck_price_alerts_condition_type CHECK (condition_type IN ('ABOVE', 'BELOW', 'CHANGE_PERCENT')),
    CONSTRAINT ck_price_alerts_target_value CHECK (
        (condition_type = 'CHANGE_PERCENT' AND target_percent IS NOT NULL)
        OR
        (condition_type IN ('ABOVE', 'BELOW') AND target_price IS NOT NULL)
    )
);

CREATE INDEX idx_market_assets_market_cap_rank ON market_assets (market_cap_rank);
CREATE INDEX idx_market_pairs_asset_id ON market_pairs (asset_id);
CREATE INDEX idx_market_candles_pair_interval_open_time ON market_candles (pair_id, interval_name, open_time DESC);
CREATE INDEX idx_market_trending_snapshot_at ON market_trending (snapshot_at DESC, id DESC);
CREATE INDEX idx_user_watchlist_items_user_id ON user_watchlist_items (user_id);
CREATE INDEX idx_price_alerts_user_id_active ON price_alerts (user_id, is_active);
